### PR TITLE
Migrated test_data_self_heal_algorithm_full_default

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_data_self_heal_algorithm_full_default.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

### CODE REVIEW

**Comment by aujjwal-redhat** [comment]
```sh

✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_data_self_heal_algorithm_full_default-arb
✔ test_data_self_heal_algorithm_full_default-arb Succeeded
✔ Running test case : test_data_self_heal_algorithm_full_default-dist-arb
✔ test_data_self_heal_algorithm_full_default-dist-arb Succeeded
Results for arbiter
Test nature : disruptive
TestName : test_data_self_heal_algorithm_full_default
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     arb     |     PASS    |        00:04:17       |      NA     |
|   dist-arb  |     PASS    |        00:04:26       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

**Comment by aujjwal-redhat** [comment]
```sh

✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_data_self_heal_algorithm_full_default-arb
✔ test_data_self_heal_algorithm_full_default-arb Succeeded
✔ Running test case : test_data_self_heal_algorithm_full_default-dist-arb
✔ test_data_self_heal_algorithm_full_default-dist-arb Succeeded
Results for arbiter
Test nature : disruptive
TestName : test_data_self_heal_algorithm_full_default
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     arb     |     PASS    |        00:03:35       |      NA     |
|   dist-arb  |     PASS    |        00:04:07       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

**Comment by nik-redhat** [comment]
You didn't enable the `features.trash` option so how is this working?
And, how come it's doing a correct check for arequal-checksum?

**Comment by aujjwal-redhat** [comment]
> You didn't enable the `features.trash` option so how is this working?
> And, how come it's doing a correct check for arequal-checksum?

I am not checking for trashcan file. arequal-checksum will work even without that.

**Comment by nik-redhat** [comment]
And, what's the output that we are getting after running the script?

**Comment by aujjwal-redhat** [comment]
> And, what's the output that we are getting after running the script?

```sh
[2021-07-22 14:45:25,777] INFO  - Start collecting arequal-checksum from all mounts
[2021-07-22 14:45:25,777] INFO  - arequal-checksum of mount 10.70.43.23:/mnt/test_data_self_heal_algorithm_full_default-dist-arb/
[2021-07-22 14:45:25,783] INFO  - arequal-checksum of mount 10.70.41.159:/mnt/test_data_self_heal_algorithm_full_default-dist-arb/
[2021-07-22 14:45:27,793] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 100\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 101\n', '\n', 'Metadata checksums\n', 'Regular files   : 3e9\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : d0f7fd9c27740b4e5fde63046a44c0\n', 'Directories     : 2f01\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 4e8f299e984d1fca\n'], 'Flag': True, 'node': '10.70.43.23', 'cmd': 'arequal-checksum /mnt/test_data_self_heal_algorithm_full_default-dist-arb/', 'error_code': 0}
[2021-07-22 14:45:27,793] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 100\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 101\n', '\n', 'Metadata checksums\n', 'Regular files   : 3e9\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : d0f7fd9c27740b4e5fde63046a44c0\n', 'Directories     : 2f01\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 4e8f299e984d1fca\n'], 'Flag': True, 'node': '10.70.41.159', 'cmd': 'arequal-checksum /mnt/test_data_self_heal_algorithm_full_default-dist-arb/', 'error_code': 0}

```

**Review by nik-redhat — APPROVED** [review]

**Pull request merged**
