### PR TITLE
Fixed test result handler

### PR DESCRIPTION
**Pull request by nik-redhat**
Updated the `testResult` value to check for value at first index, as the value passed for `TEST_RES` is a list.

Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
```
Results for glusterd
Test nature : disruptive
TestName : test_default_max_bricks_per_process
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:25       |      NA     |
|     dist    |     PASS    |        00:00:22       |      NA     |
|     arb     |     PASS    |        00:00:24       |      NA     |
|     disp    |     PASS    |        00:00:24       |      NA     |
|   dist-rep  |     PASS    |        00:00:29       |      NA     |
|   dist-arb  |     PASS    |        00:00:28       |      NA     |
|  dist-disp  |     PASS    |        00:00:28       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   7   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 03 minutes 15 seconds
✔ Tearing down successful.
```

**Comment by nik-redhat** [comment]
Did a nonDisruptive TC check as well:
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:06       |      NA     |
|     rep     |     PASS    |        00:00:07       |      NA     |
|     arb     |     PASS    |        00:00:07       |      NA     |
|     disp    |     PASS    |        00:00:07       |      NA     |
|   dist-rep  |     PASS    |        00:00:10       |      NA     |
|   dist-arb  |     PASS    |        00:00:11       |      NA     |
|  dist-disp  |     PASS    |        00:00:07       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:08       |      NA     |
|     rep     |     PASS    |        00:00:08       |      NA     |
|     disp    |     PASS    |        00:00:08       |      NA     |
|     arb     |     PASS    |        00:00:08       |      NA     |
|   dist-rep  |     PASS    |        00:00:14       |      NA     |
|   dist-arb  |     PASS    |        00:00:15       |      NA     |
|  dist-disp  |     PASS    |        00:00:08       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for glusterd
Test nature : nonDisruptive
TestName : test_gluster_does_not_do_posix_lock_when_multiple_client
+-------------+-------------+-----------------------+--------------------------------------------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) |                   Skip Reason                    |
+-------------+-------------+-----------------------+--------------------------------------------------+
|     dist    |     SKIP    |        00:00:28       | The test case requires 2 clients to run the test |
|     rep     |     SKIP    |        00:00:28       | The test case requires 2 clients to run the test |
|     arb     |     SKIP    |        00:00:29       | The test case requires 2 clients to run the test |
|     disp    |     SKIP    |        00:00:29       | The test case requires 2 clients to run the test |
|   dist-rep  |     SKIP    |        00:00:36       | The test case requires 2 clients to run the test |
|   dist-arb  |     SKIP    |        00:00:35       | The test case requires 2 clients to run the test |
|  dist-disp  |     SKIP    |        00:00:28       | The test case requires 2 clients to run the test |
+-------------+-------------+-----------------------+--------------------------------------------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   7   |
|              Tests Ran               |   14  |
|            Tests Skipped             |   7   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 03 minutes 30 seconds
✔ Tearing down successful.
```

**Comment by srijan-sivakumar** [comment]
@nik-redhat can you also run a test case which actually gets skipped. Just to be sure with the change.

**Comment by nik-redhat** [comment]
> > @nik-redhat don't we need to change in result-handler ?
> 
> Result handler uses this test stat data to determine the result aggregation.

Ahh...we won't be needing an update in the result handler because we are saving the value as a string.

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
