### PR TITLE
[Core] Changing default dirs

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Changed the default dir for the following,
1. The logs will now be present at `/var/log/redant`
by default.
2. The io scripts will be placed at
`/usr/share/redant/script`.

Fixes: #988 

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Review by nik-redhat — COMMENTED** [review]
I think there are many other ops and TCs which use the path of the `file_dir_ops` directly. All of them need to be updated. The PR will be a bit long, it seems :sweat_smile:

**Comment by Sheetalpamecha** [comment]
Yes, was just checking with one such TC and it fails after applying this patch
```
✔ Running test case : test_afr_with_snapshot-rep
✖ test_afr_with_snapshot-rep Failed
✔ Running test case : test_afr_with_snapshot-dist-rep
✖ test_afr_with_snapshot-dist-rep Failed
Results for afr
Test nature : disruptive
TestName : test_afr_with_snapshot
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     FAIL    |        00:00:53       |      NA     |
|   dist-rep  |     FAIL    |        00:00:56       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
```

**Review by Sheetalpamecha — DISMISSED** [review]
Otherwise,  The dir change for log and files is successful. Just need to take care of TC using direct /tmp path

**Comment by srijan-sivakumar** [comment]
> Otherwise, The dir change for log and files is successful. Just need to take care of TC using direct /tmp path

Ack. Will make changes in the TCs.

**Comment by nik-redhat** [comment]
@srijan-sivakumar can you please add the output of a TC for which the path update was made, to confirm if everything is working fine?

**Comment by srijan-sivakumar** [comment]
> @srijan-sivakumar can you please add the output of a TC for which the path update was made, to confirm if everything is working fine?

You mean to say all cases wherein the path was modified right ?

**Comment by nik-redhat** [comment]
No no, any one out of them would do.

**Comment by nik-redhat** [comment]
But, if you can check all of them, then that is fine as well. Depends on you.

**Comment by srijan-sivakumar** [comment]
```console
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/afr/test_client_side_quorum_with_cross2.py -ll D
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_client_side_quorum_with_cross2-rep
✔ test_client_side_quorum_with_cross2-rep Succeeded
✔ Running test case : test_client_side_quorum_with_cross2-dist-rep
✔ test_client_side_quorum_with_cross2-dist-rep Succeeded
Results for afr
Test nature : disruptive
TestName : test_client_side_quorum_with_cross2
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:40       |      NA     |
|   dist-rep  |     PASS    |        00:00:46       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   2   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 01 minutes 43 seconds
✔ Tearing down successful.
```

**Comment by srijan-sivakumar** [comment]
> But, if you can check all of them, then that is fine as well. Depends on you.

Added one tc run. Mostly the change is either a direct replacement of the path or using a variable to replace the value in the command.

**Review by nik-redhat — APPROVED** [review]

**Pull request merged**
