### PR TITLE
Migrated TC test_remove_brick_no_commit_followed_by_rebalance.py

### PR DESCRIPTION
**Pull request by Sheetalpamecha**
Migrated TC [test_remove_brick_no_commit_followed_by_rebalance.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_no_commit_followed_by_rebalance.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

### CODE REVIEW

**Comment by Sheetalpamecha** [comment]
Hi @nik-redhat. This TC is failing continuously for remove-brick status. Have you encountered such errors and do you know how to resolve them?


redant.log
```
[2021-10-06 17:17:49,249] INFO  - Running gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 start --mode=script --xml on 10.70.42.191
[2021-10-06 17:18:07,939] DEBUG  -  {'msg': {'opRet': '0', 'opErrno': '0', 'opErrstr': 'Remove Brick start successful', 'volRemoveBrick': {'task-id': '1245eda7-980a-472a-8c71-ced4676b5f4b'}}, 'Flag': True, 'node': '10.70.42.191', 'cmd': 'gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 start --mode=script --xml', 'error_code': 0}
[2021-10-06 17:18:07,940] INFO  - Running gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 status --mode=script --xml on 10.70.42.191
[2021-10-06 17:18:09,819] DEBUG  -  {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'Rebalance not started for volume test_remove_brick_no_commit_followed_by_rebalance-dist.', 'volRemoveBrick': None}, 'Flag': True, 'node': '10.70.42.191', 'cmd': 'gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 status --mode=script --xml', 'error_code': 0}
[2021-10-06 17:18:09,819] INFO  - Running gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 stop --mode=script --xml on 10.70.42.191
[2021-10-06 17:18:11,687] DEBUG  -  {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'Rebalance not started for volume test_remove_brick_no_commit_followed_by_rebalance-dist.', 'volRemoveBrick': None}, 'Flag': True, 'node': '10.70.42.191', 'cmd': 'gluster vol remove-brick test_remove_brick_no_commit_followed_by_rebalance-dist  10.70.43.139:/home/spamecha/bricks/test_remove_brick_no_commit_followed_by_rebalance-dist-2 stop --mode=script --xml', 'error_code': 0}
```


glusterd.log
```
[2021-10-06 11:47:50.997862 +0000] I [MSGID: 106496] [glusterd-handshake.c:954:__server_getspec] 0-management: Received mount request for volume /test_remove_brick_no_commit_followed_by_rebalance-dist
[2021-10-06 11:48:09.207140 +0000] W [glusterd-mgmt.c:223:gd_mgmt_v3_pre_validate_fn] 0-management: Rebalance Prevalidate Failed
[2021-10-06 11:48:09.207170 +0000] E [MSGID: 106121] [glusterd-mgmt.c:1015:glusterd_mgmt_v3_pre_validate] 0-management: Pre Validation failed for operation Rebalance on local node
[2021-10-06 11:48:09.207181 +0000] E [MSGID: 106121] [glusterd-mgmt.c:2481:glusterd_mgmt_v3_initiate_all_phases_with_brickop_phase] 0-management: Pre Validation Failed
[2021-10-06 11:48:11.094848 +0000] W [glusterd-mgmt.c:223:gd_mgmt_v3_pre_validate_fn] 0-management: Rebalance Prevalidate Failed
[2021-10-06 11:48:11.094890 +0000] E [MSGID: 106121] [glusterd-mgmt.c:1015:glusterd_mgmt_v3_pre_validate] 0-management: Pre Validation failed for operation Rebalance on local node
[2021-10-06 11:48:11.094904 +0000] E [MSGID: 106121] [glusterd-mgmt.c:2481:glusterd_mgmt_v3_initiate_all_phases_with_brickop_phase] 0-management: Pre Validation Failed
[2021-10-06 11:48:46.284275 +0000] I [MSGID: 106482] [glusterd-brick-ops.c:270:__glusterd_handle_add_brick] 0-management: Received add brick req
[2021-10-06 11:48:46.286423 +0000] I [MSGID: 106061] [glusterd-utils.c:14965:glusterd_add_peers_to_auth_list] 0-management: auth allow list is not set [No such file or directory]
[2021-10-06 11:48:46.286495 +0000] E [MSGID: 106061] [glusterd-server-quorum.c:257:glusterd_is_volume_in_server_quorum] 0-management: Dict get failed [{Key=cluster.server-quorum-type}, {errno=2}, {error=No such file or directory}]
```

**Comment by nik-redhat** [comment]
Ok, I think the issue is similar to what I faced for this TC #1136 .
You can try using the custom `setup_test` and change the vol_name being used to something like `testvol_{self.volume_type}` as I have done in that TC and see if that helps (I think it should).

**Comment by nik-redhat** [comment]
This seems to be an issue (or some weird check) in gluster itself.

**Comment by Sheetalpamecha** [comment]
> Ok, I think the issue is similar to what I faced for this TC #1136 . You can try using the custom `setup_test` and change the vol_name being used to something like `testvol_{self.volume_type}` as I have done in that TC and see if that helps (I think it should).

Yes It did worked. Thank you

**Comment by Sheetalpamecha** [comment]
```
Results for dht
Test nature : disruptive
TestName : test_remove_brick_no_commit_followed_by_rebalance
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:19:56       |      NA     |
|  dist-disp  |     PASS    |        00:11:46       |      NA     |
|   dist-arb  |     PASS    |        00:11:00       |      NA     |
|     dist    |     PASS    |        00:07:24       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   4   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 52 minutes 05 seconds
✔ Tearing down successful.
```

**Pull request merged**
