### PR TITLE
Migrated test_heal_fail_1x3

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_heal_fail_1x3.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

### CODE REVIEW

**Comment by aujjwal-redhat** [comment]
```sh

Results for afr
Test nature : disruptive
TestName : test_heal_fail_1x3
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:41       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat Things LGTM its just I'd wait till the arequal-checksum script is installed in the CI servers..

**Comment by aujjwal-redhat** [comment]
> @aujjwal-redhat Things LGTM its just I'd wait till the arequal-checksum script is installed in the CI servers..

ack

**Comment by nik-redhat** [comment]
@srijan-sivakumar any updates on the arequal-checksum script installation?

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
