### PR TITLE
Migrated TC test_self_heal_50k_files_heal_command_by_add_brick

### PR DESCRIPTION
**Pull request by nik-redhat**
Migrated TC [test_self_heal_50k_files_heal_command_by_add_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_50k_files_heal_command_by_add_brick.py)

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
A similar TC that deals with 50k files.

**Comment by srijan-sivakumar** [comment]
@nik-redhat I think it is better to open an issue on async timeout. So that we can plan and work on it.

**Comment by nik-redhat** [comment]
> @nik-redhat I think it is better to open an issue on async timeout. So that we can plan and work on it.

I have opened issue #878 for the same.

**Comment by nik-redhat** [comment]
I think we are good to merge this TC if the logic looks fine to you all. I will send out a separate PR for the timeout update.

**Review by srijan-sivakumar — APPROVED** [review]
@nik-redhat LGTM. We can test this properly once we have the timeout for async. For now, taking in this patch.

**Pull request merged**
