### PR TITLE
Migrated TC test_verify_df_output

### PR DESCRIPTION
**Pull request by nik-redhat**
Migrated TC [test_verify_df_output](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_verify_df_output.py)

Also, updated the `form_brick_cmd` function to take the unused bricks in case of multiple bricks per node

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
```
Results for glusterd
Test nature : disruptive
TestName : test_verify_df_output
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:17:23       |      NA     |
|   dist-rep  |     FAIL    |        00:33:39       |      NA     |
|     disp    |     PASS    |        00:04:59       |      NA     |
|  dist-disp  |     FAIL    |        00:05:26       |      NA     |
|     arb     |     PASS    |        00:07:01       |      NA     |
|   dist-arb  |     FAIL    |        00:23:34       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   6   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   |  50.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         |  50.0 |
+--------------------------------------+-------+
Total Time Taken : 01 hours 32 minutes 20 seconds
✔ Tearing down successful.
```

The tests for dist-* volumes are failing because they require 6 servers having 2 bricks each so that on expanding the volume we get new bricks instead of the old one's. I will add a skip for the test if the configuration is not matching for such volume types.

**Comment by srijan-sivakumar** [comment]
> |   dist-arb  |     FAIL    |        00:23:34       |      NA     |

Yes..that would be better as if we see the numbers, around 66% time is spent on failing scenario...so a skip for now will come in handy.

**Comment by nik-redhat** [comment]
```
Results for glusterd
Test nature : disruptive
TestName : test_verify_df_output
+-------------+-------------+-----------------------+--------------------------------------------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) |                   Skip Reason                    |
+-------------+-------------+-----------------------+--------------------------------------------------+
|     rep     |     PASS    |        00:06:52       |                        NA                        |
|   dist-rep  |     SKIP    |        00:00:26       | The test case requires 6 servers to run the test |
|     disp    |     PASS    |        00:04:54       |                        NA                        |
|  dist-disp  |     SKIP    |        00:00:26       | The test case requires 6 servers to run the test |
|     arb     |     PASS    |        00:16:58       |                        NA                        |
|   dist-arb  |     SKIP    |        00:00:26       | The test case requires 6 servers to run the test |
+-------------+-------------+-----------------------+--------------------------------------------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   3   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   0   |
|            Tests Skipped             |   3   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 30 minutes 17 seconds
✔ Tearing down successful.
```

**Comment by nik-redhat** [comment]
6 servers, more than 2 bricks per node:
```
Results for glusterd
Test nature : disruptive
TestName : test_verify_df_output
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:07:12       |      NA     |
|   dist-rep  |     PASS    |        00:13:42       |      NA     |
|     disp    |     PASS    |        00:05:04       |      NA     |
|  dist-disp  |     PASS    |        00:13:39       |      NA     |
|     arb     |     PASS    |        00:07:05       |      NA     |
|   dist-arb  |     PASS    |        00:13:40       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   6   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 01 hours 00 minutes 36 seconds
✔ Tearing down successful.
```

**Comment by nik-redhat** [comment]
```
Results for glusterd
Test nature : disruptive
TestName : test_verify_df_output
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:07:12       |      NA     |
|   dist-rep  |     PASS    |        00:13:41       |      NA     |
|     disp    |     PASS    |        00:01:07       |      NA     |
|  dist-disp  |     PASS    |        00:13:37       |      NA     |
|     arb     |     PASS    |        00:07:06       |      NA     |
|   dist-arb  |     PASS    |        00:13:35       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   6   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 56 minutes 31 seconds
✔ Tearing down successful.
```

**Comment by nik-redhat** [comment]
This PR is ready for review. II have tested multiple scenarios with it, which needs a multi-brick setup or doesn't.

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
